import './globals.css';
import { Inter } from 'next/font/google';
import AuthContextProvider from '@/modules/auth_provider';
import WebSocketProvider from '@/modules/websocket_provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <WebSocketProvider>
            <div className="flex flex-col md:flex-row h-full min-h-screen font-sans">
              {children}
            </div>
          </WebSocketProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
